import { Model } from 'mongoose';
import { JobTemplateDocument } from './models/job-template.schema';
import { JobRequisitionDocument } from './models/job-requisition.schema';
import { ApplicationDocument } from './models/application.schema';
import { ApplicationStatusHistoryDocument } from './models/application-history.schema';
import { InterviewDocument } from './models/interview.schema';
import { AssessmentResultDocument } from './models/assessment-result.schema';
import { OfferDocument } from './models/offer.schema';
import { ContractDocument } from './models/contract.schema';
import { OnboardingDocument } from './models/onboarding.schema';
import { TerminationRequestDocument } from './models/termination-request.schema';
import { ClearanceChecklistDocument } from './models/clearance-checklist.schema';
import { ReferralDocument } from './models/referral.schema';
import { DocumentDocument } from './models/document.schema';
import { CreateJobTemplateDto, UpdateJobTemplateDto, CreateJobRequisitionDto, UpdateJobRequisitionDto, CreateApplicationDto, UpdateApplicationStageDto, UpdateApplicationStatusDto, CreateInterviewDto, UpdateInterviewDto, CreateAssessmentResultDto, CreateOfferDto, CreateContractDto, CreateOnboardingDto, UpdateOnboardingTaskDto, CreateTerminationRequestDto, UpdateClearanceChecklistDto, CreateReferralDto, CreateDocumentDto, UpdateDocumentDto } from './dto';
import { InterviewStatus } from './enums/interview-status.enum';
import { OfferResponseStatus } from './enums/offer-response-status.enum';
import { ApprovalStatus } from './enums/approval-status.enum';
import { TerminationStatus } from './enums/termination-status.enum';
import { EmployeeProfileService } from '../employee-profile/employee-profile.service';
export declare class RecruitmentService {
    private jobTemplateModel;
    private jobRequisitionModel;
    private applicationModel;
    private applicationHistoryModel;
    private interviewModel;
    private assessmentResultModel;
    private offerModel;
    private contractModel;
    private onboardingModel;
    private terminationRequestModel;
    private clearanceChecklistModel;
    private referralModel;
    private documentModel;
    private employeeProfileService;
    constructor(jobTemplateModel: Model<JobTemplateDocument>, jobRequisitionModel: Model<JobRequisitionDocument>, applicationModel: Model<ApplicationDocument>, applicationHistoryModel: Model<ApplicationStatusHistoryDocument>, interviewModel: Model<InterviewDocument>, assessmentResultModel: Model<AssessmentResultDocument>, offerModel: Model<OfferDocument>, contractModel: Model<ContractDocument>, onboardingModel: Model<OnboardingDocument>, terminationRequestModel: Model<TerminationRequestDocument>, clearanceChecklistModel: Model<ClearanceChecklistDocument>, referralModel: Model<ReferralDocument>, documentModel: Model<DocumentDocument>, employeeProfileService: EmployeeProfileService);
    createJobTemplate(createDto: CreateJobTemplateDto): Promise<JobTemplateDocument>;
    findAllJobTemplates(filters?: any): Promise<JobTemplateDocument[]>;
    findJobTemplateById(id: string): Promise<JobTemplateDocument>;
    updateJobTemplate(id: string, updateDto: UpdateJobTemplateDto): Promise<JobTemplateDocument>;
    deleteJobTemplate(id: string): Promise<void>;
    createJobRequisition(createDto: CreateJobRequisitionDto): Promise<JobRequisitionDocument>;
    findAllJobRequisitions(filters?: any): Promise<JobRequisitionDocument[]>;
    findJobRequisitionById(id: string): Promise<JobRequisitionDocument>;
    updateJobRequisition(id: string, updateDto: UpdateJobRequisitionDto): Promise<JobRequisitionDocument>;
    publishJobRequisition(id: string): Promise<JobRequisitionDocument>;
    closeJobRequisition(id: string): Promise<JobRequisitionDocument>;
    previewJobRequisition(id: string): Promise<any>;
    deleteJobRequisition(id: string): Promise<void>;
    createApplication(createDto: CreateApplicationDto): Promise<ApplicationDocument>;
    findAllApplications(filters?: any): Promise<ApplicationDocument[]>;
    findApplicationById(id: string): Promise<ApplicationDocument>;
    updateApplicationStage(id: string, updateDto: UpdateApplicationStageDto): Promise<ApplicationDocument>;
    updateApplicationStatus(id: string, updateDto: UpdateApplicationStatusDto): Promise<ApplicationDocument>;
    assignHrToApplication(id: string, hrId: string): Promise<ApplicationDocument>;
    getApplicationHistory(id: string): Promise<ApplicationStatusHistoryDocument[]>;
    getApplicationCommunicationLogs(id: string): Promise<any[]>;
    recordConsent(id: string, consentDto: any): Promise<any>;
    getConsentStatus(id: string): Promise<any>;
    createInterview(createDto: CreateInterviewDto): Promise<InterviewDocument>;
    findAllInterviews(filters?: any): Promise<InterviewDocument[]>;
    findInterviewById(id: string): Promise<InterviewDocument>;
    updateInterview(id: string, updateDto: UpdateInterviewDto): Promise<InterviewDocument>;
    updateInterviewStatus(id: string, status: InterviewStatus): Promise<InterviewDocument>;
    createAssessmentResult(createDto: CreateAssessmentResultDto): Promise<AssessmentResultDocument>;
    getInterviewAssessment(id: string): Promise<AssessmentResultDocument | null>;
    sendCalendarInvite(id: string): Promise<any>;
    createOffer(createDto: CreateOfferDto): Promise<OfferDocument>;
    findAllOffers(filters?: any): Promise<OfferDocument[]>;
    findOfferById(id: string): Promise<OfferDocument>;
    updateOffer(id: string, updateDto: any): Promise<OfferDocument>;
    updateOfferResponse(id: string, response: OfferResponseStatus): Promise<OfferDocument>;
    updateOfferApproval(id: string, approverId: string, status: ApprovalStatus): Promise<OfferDocument>;
    signOffer(id: string, signerType: string, signature: string): Promise<OfferDocument>;
    generateOfferPDF(id: string): Promise<any>;
    sendOfferToCandidate(id: string): Promise<any>;
    createContract(createDto: CreateContractDto): Promise<ContractDocument>;
    findAllContracts(filters?: any): Promise<ContractDocument[]>;
    findContractById(id: string): Promise<ContractDocument>;
    signContract(id: string, signerType: string, signatureUrl: string): Promise<ContractDocument>;
    generateContractPDF(id: string): Promise<any>;
    getContractByOfferId(offerId: string): Promise<ContractDocument | null>;
    createOnboarding(createDto: CreateOnboardingDto): Promise<OnboardingDocument>;
    findOnboardingByEmployeeId(employeeId: string): Promise<OnboardingDocument | null>;
    updateOnboardingTask(id: string, taskId: string, updateDto: UpdateOnboardingTaskDto): Promise<OnboardingDocument>;
    completeOnboarding(id: string): Promise<OnboardingDocument>;
    getOnboardingTasks(id: string): Promise<any[]>;
    createTerminationRequest(createDto: CreateTerminationRequestDto): Promise<TerminationRequestDocument>;
    findAllTerminationRequests(filters?: any): Promise<TerminationRequestDocument[]>;
    findTerminationRequestById(id: string): Promise<TerminationRequestDocument>;
    updateTerminationStatus(id: string, status: TerminationStatus): Promise<TerminationRequestDocument>;
    getClearanceChecklist(id: string): Promise<ClearanceChecklistDocument | null>;
    updateClearanceChecklist(id: string, updateDto: UpdateClearanceChecklistDto): Promise<ClearanceChecklistDocument>;
    createReferral(createDto: CreateReferralDto): Promise<ReferralDocument>;
    findAllReferrals(filters?: any): Promise<ReferralDocument[]>;
    findReferralById(id: string): Promise<ReferralDocument>;
    updateReferral(id: string, updateDto: any): Promise<ReferralDocument>;
    deleteReferral(id: string): Promise<void>;
    createDocument(createDto: CreateDocumentDto & {
        filePath: string;
        fileName: string;
        fileSize: number;
    }): Promise<DocumentDocument>;
    findAllDocuments(filters?: any): Promise<DocumentDocument[]>;
    findDocumentById(id: string): Promise<DocumentDocument>;
    updateDocument(id: string, updateDto: UpdateDocumentDto): Promise<DocumentDocument>;
    deleteDocument(id: string): Promise<void>;
    downloadDocument(id: string): Promise<any>;
    getRecruitmentOverview(filters?: any): Promise<any>;
    getRecruitmentMetrics(filters?: any): Promise<any>;
    getPipelineView(filters?: any): Promise<any>;
    getRequisitionMetrics(id: string): Promise<any>;
    getApplicationsByStage(requisitionId?: string): Promise<any>;
    getApplicationsByStatus(requisitionId?: string): Promise<any>;
    getTimeToHireMetrics(requisitionId?: string): Promise<any>;
    private createApplicationHistoryEntry;
}
