import { Model } from 'mongoose';
import { AppraisalTemplate, AppraisalTemplateDocument } from './models/appraisal-template.schema';
import { CreateAppraisalTemplateDto } from './DTOs/CreateAppraisalTemplate.dto';
import { AppraisalCycle, AppraisalCycleDocument } from './models/appraisal-cycle.schema';
import { CreateAppraisalCycleDTO } from './DTOs/CreateAppraisalCycle.dto';
import { AppraisalAssignmentDocument, AppraisalAssignment } from './models/appraisal-assignment.schema';
import { CreateAppraisalAssignmentDTO } from './DTOs/CreateAppraisalAssignment.dto';
import { AppraisalRecord, AppraisalRecordDocument } from './models/appraisal-record.schema';
import { CreateAppraisalRecordDTO } from './DTOs/CreateAppraisalRecord.dto';
import { UpdateAppraisalRecordDto } from './DTOs/UpdateAppraisalRecord.dto';
import { AppraisalDispute, AppraisalDisputeDocument } from './models/appraisal-dispute.schema';
import { CreateAppraisalDisputeDTO } from './DTOs/CreateAppraisalDispute.dto';
import { UpdateAppraisalDisputeDto } from './DTOs/UpdateAppraisalDispute.dto';
import { EmployeeProfileDocument } from '../employee-profile/models/employee-profile.schema';
import { AppraisalRecordStatus } from './enums/performance.enums';
import { Types } from 'mongoose';
export declare class PerformanceService {
    private templateModel;
    private cycleModel;
    private assignmentModel;
    private recordModel;
    private disputeModel;
    private employeeProfileModel;
    constructor(templateModel: Model<AppraisalTemplateDocument>, cycleModel: Model<AppraisalCycleDocument>, assignmentModel: Model<AppraisalAssignmentDocument>, recordModel: Model<AppraisalRecordDocument>, disputeModel: Model<AppraisalDisputeDocument>, employeeProfileModel: Model<EmployeeProfileDocument>);
    createTemplate(dto: CreateAppraisalTemplateDto): Promise<AppraisalTemplate>;
    getAllTemplates(): Promise<AppraisalTemplate[]>;
    createCycle(dto: CreateAppraisalCycleDTO): Promise<AppraisalCycle>;
    getAllCycles(): Promise<AppraisalCycle[]>;
    assignAppraisalsBulk(dtos: CreateAppraisalAssignmentDTO[]): Promise<AppraisalAssignment[]>;
    getAssignmentsForManager(managerId: string): Promise<AppraisalAssignment[]>;
    getAllAssignments(): Promise<AppraisalAssignment[]>;
    createAppraisalRecord(dto: CreateAppraisalRecordDTO): Promise<AppraisalRecord>;
    getRecords(): Promise<AppraisalRecord[]>;
    updateAppraisalRecord(recordId: string, dto: UpdateAppraisalRecordDto): Promise<AppraisalRecord>;
    getDashboard(cycleId: string): Promise<any[]>;
    getAppraisalProgress(cycleId: string): Promise<AppraisalAssignment[]>;
    getEmployeeAppraisals(employeeId: string): Promise<AppraisalRecord[]>;
    createAppraisalDispute(dto: CreateAppraisalDisputeDTO): Promise<AppraisalDispute>;
    updateAppraisalDispute(disputeId: string, dto: UpdateAppraisalDisputeDto): Promise<AppraisalDispute>;
    getAllDisputes(): Promise<AppraisalDispute[]>;
    publishAppraisal(recordId: string, publishedByEmployeeId: string): Promise<AppraisalRecord>;
    getEmployeeAppraisalHistory(employeeId: string): Promise<AppraisalRecord[]>;
    generateAppraisalReport(cycleId: string): Promise<{
        cycleId: Types.ObjectId;
        cycleName: string;
        cycleType: import("./enums/performance.enums").AppraisalTemplateType;
        startDate: Date;
        endDate: Date;
        totalAppraisals: number;
        publishedAppraisals: number;
        averageScore: number;
        scoreDistribution: {
            excellent: number;
            good: number;
            satisfactory: number;
            needsImprovement: number;
        };
        records: {
            employeeId: Types.ObjectId;
            score: number | undefined;
            rating: string | undefined;
            status: AppraisalRecordStatus;
        }[];
    }>;
}
